### ISSUE TITLE
requests.exceptions.SSLError: bad handshake: SysCallError(54, 'ECONNRESET')

### ISSUE THREAD

**Issue by mklatsky** [francescou/docker-compose-search#1] opened 2016-04-05 16:30 UTC
I have just installed docker-compose-search, and when I run a search ('docker-compose-search rocket' for example), I receive the following error:

```
$ sudo docker-compose-search rocket
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose-search", line 54, in <module>
    search(' '.join(sys.argv[1:]))
  File "/usr/local/bin/docker-compose-search", line 26, in search
    params={'query': query}, headers={'x-key': 'default'})
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: SysCallError(54, 'ECONNRESET')
```

This is on OSX 10.11.4, python 2.7.8.

Any guidance would be helpful. Thank you.

**Comment by francescou** [comment] 2016-04-05 19:01
Hello Michael,
I can't reproduce the issue but I've installed docker-compose-search on a _python:2.7.8_ container, even if it works there are several warnings about the connection.

On the [urllib3 documentation](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.) I've read about some restriction on the ssl module using python version < 2.7.9

Could you please try to upgrade python and see if it works?

Thanks

Francesco

**Comment by francescou** [comment] 2016-04-08 09:04
Hello Michael,
did you solve the issue?

**Comment by mklatsky** [comment] 2016-04-08 13:57
I have upgraded python to 2.7.11, and urllib3 is at 1.15, and I still have the same error.

Unfortunately the issue was not solved.

**Comment by francescou** [comment] 2016-04-08 14:16
could you please tell me what version of openssl you have installed?

`openssl version`

**Comment by mklatsky** [comment] 2016-04-08 14:17
openssl version
OpenSSL 0.9.8zh 14 Jan 2016

**Comment by francescou** [comment] 2016-04-08 14:41
I think that the problem could be due to an outdated openssl version. Could you upgrade it?

**Comment by francescou** [comment] 2016-04-11 08:55
any news?

**Comment by mklatsky** [comment] 2016-04-12 14:40
I don't have anything to update right now- although I found something interesting which may be impacting this. When I run 'openssl version', the version reported is OpenSSL 0.9.8zh 14 Jan 2016.

However, the version available from home-brew is 1.0.2g. If I try to 'brew install openssl', I receive the notice: Warning: openssl-1.0.2g already installed.

I will try to unwind this as it may be tangentially related to the core issue.

**Comment by francescou** [comment] 2016-04-12 20:29
I've done some quick test on my girlfriend macbook.

it seems that older versions of openssl can't connect to https://www.composeregistry.com so I've upgraded to 1.0.2g and it works:

```
/usr/local/Cellar/openssl/1.0.2g/bin/openssl s_client -connect www.composeregistry.com:443
```

I guess you should link the newer openssl  to /usr/local/bin in place of the previous openssl executable

**Comment by francescou** [comment] 2016-04-16 12:26
I'm closing the issue since it seems it's not related to my project, feel free to reopen if necessary

**Closed as completed by francescou** 2016-04-16 12:26 UTC

**Comment by cherryz** [comment] 2017-04-09 07:52
@francescou @mklatsky I have the same problem, did you solve it?

**Comment by jrostamir** [comment] 2019-06-03 12:36
check the following [link](https://stackoverflow.com/questions/43846689/sslerror-bad-handshake-syscallerror54-econnreset). Hope it helps.
